# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b2b76fd2756e1f91dd56b05a5c6df915be7dcd573febe79bfe7eb79089343349d9062b1aeccb9670e3b6b73eb374964c622768d8370bb58a121b685278a8dd5

test:
  secret_key_base: d233664eb4fde9cccf9edd961bfca8362833f59ca401522be331059cd9fc24d6a65e5c46d53552355980359c1f45a27c4b19e25c99f2b07302c434ebe62e191c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
